# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98486964f61602f75d23d2722b69f4ae14b53c7c0368493873257a6e7f2a345064776e30f54a690a3d5689053b35cc34bf7d8fabc72f57e9bb9d88a3c2d3b786

test:
  secret_key_base: a6d96d4d4057fa316e7dbd1079fb8ba796d76b7fa8cb3833e2dc78d54c3357599348fc3ec934e0085161360dc699165e529a4d95ebb219d9307fb5d1164209db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
